apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: channel-connect-data
  namespace: channel-connect
spec:
  storageClassName: standard-rwo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
