apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: channel-connect

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - secret.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: channel-connect
    newName: channel-connect
    newTag: local
