apiVersion: v1
kind: Service
metadata:
  name: channel-connect
  namespace: channel-connect
  labels:
    app: channel-connect
spec:
  type: ClusterIP
  selector:
    app: channel-connect
  ports:
    - name: http
      port: 80
      targetPort: http
